### ISSUE TITLE
Server does not start according to instruction.

### ISSUE THREAD

**Issue by const** [basarat/react-typescript#3]
I have tried `npm start` from current sources. and server did not started. Nothing were listenting at localhost:8080.

I replaced start instruction in package.json with ` "start": "webpack-dev-server --hot --inline --no-info"` from book. And server started to work on 8080.

Also, please specify URL where server should be working. It took me some time to figure out that it should be localhost:8080.

**Comment by basarat** [comment]
Done : https://basarat.gitbooks.io/typescript/content/docs/quick/browser.html#develop-your-amazing-application :rose:
