### ISSUE TITLE
Question: What is React.SFC?

### ISSUE THREAD

**Issue by styfle** [basarat/react-typescript#4]
This is the first I'm seeing [React.SFC](https://github.com/basarat/react-typescript/blob/master/src/app/app.tsx).

Are there any docs on this feature?

**Comment by basarat** [comment]
> Are there any docs on this feature?

I am the docs. Kidding (not kidding (or am I)), I don't know anymore. 😂 I should add a detailed react section https://basarat.gitbooks.io/typescript/content/docs/jsx/tsx.html at some point. I also have an egghead course that mentions it. I make the scripts available for those keen to read : https://github.com/basarat/typescript-react/tree/master/02%20stateless :rose: 

Docs (the code shall set thee free :rose:): https://github.com/DefinitelyTyped/DefinitelyTyped/blob/4bab2f77836bbf8cf2961b9c0471115cdb19613a/types/react/index.d.ts#L323 :rose:

**Comment by styfle** [comment]
So is the idea that you don't have to define `children` as a property?

### Before

```ts
interface Props {
  className: string;
  children?: ReactNode;
}
const Heading = (props: Props) => (
  <h1 className={props.className}>{props.children}</h1>
);
```

### After

```ts
interface Props {
  className: string;
}
const Heading: React.SFC<Props> = (props) => (
  <h1 className={props.className}>{props.children}</h1>
);
```

The second one seems like it's a little more to type then the first one.

**Comment by basarat** [comment]
> So is the idea that you don't have to define children as a property?

Yes. And other things like `displayName` :rose:

```ts
interface Props {
  className: string;
}
const Heading: React.SFC<Props> = (props) => (
  <h1 className={props.className}>{props.children}</h1>
);
Heading.displayName = 'heading'; // etc
```

**Comment by styfle** [comment]
I’ve never used or heard of displayName! I’m learning so much 😁

https://reactjs.org/docs/higher-order-components.html#convention-wrap-the-display-name-for-easy-debugging

**Comment by basarat** [comment]
Added https://basarat.gitbooks.io/typescript/content/docs/jsx/react.html :rose:
